# Generated by Django 6.0.5 on 2026-06-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mood', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('neutral', 'Neutral'), ('stressed', 'Stressed'), ('low', 'Low'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
                ('read_time', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('video_link', models.URLField()),
                ('music_link', models.URLField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
