# Generated by Django 6.0.2 on 2026-05-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalsignal',
            name='source',
            field=models.CharField(choices=[('journal', 'Journal'), ('chat', 'Chat'), ('assessment', 'Assessment')], max_length=20),
        ),
    ]
