import React, { useState, useEffect, useRef } from 'react';
import { 
  View, Text, TextInput, TouchableOpacity, ScrollView, Animated, 
  Easing, Platform, ActivityIndicator, Modal, KeyboardAvoidingView, Keyboard
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import * as Speech from 'expo-speech';
import { useAudioRecorder, AudioModule, RecordingPresets } from 'expo-audio';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import Svg, { Circle, Path } from 'react-native-svg';
import { 
  Menu, Plus, MessageSquare, Pin, Trash2, Send, 
  Mic, Volume2, ShieldAlert, HeartHandshake, MicOff, Search, Download
} from 'lucide-react-native';
import { Button } from 'heroui-native';
import { usePreferences } from '@/context/PreferencesContext';
import apiClient from '@/api/apiClient';

// ==========================================
// SMERA SVG NATIVE COMPONENT
// ==========================================
const SmeraAvatar = ({ size = 36 }) => (
  <View className="rounded-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 items-center justify-center overflow-hidden shadow-sm" style={{ width: size, height: size }}>
    <Svg width="100%" height="100%" viewBox="0 0 100 100" fill="none">
      <Circle cx="50" cy="50" r="45" fill="#EEF2FF" stroke="#C7D2FE" strokeWidth="2"/>
      <Circle cx="35" cy="45" r="4" fill="#4F46E5" />
      <Circle cx="65" cy="45" r="4" fill="#4F46E5" />
      <Path d="M40 65C40 65 45 70 50 70C55 70 60 65 60 65" stroke="#4F46E5" strokeWidth="3.5" strokeLinecap="round"/>
      <Circle cx="30" cy="55" r="5" fill="#FED7AA" />
      <Circle cx="70" cy="55" r="5" fill="#FED7AA" />
    </Svg>
  </View>
);

// ==========================================
// TYPES
// ==========================================
interface Helpline { name: string; phone: string; }
interface ActionCard {
  type: string; title: string; description?: string;
  url?: string; consultation_url?: string; helplines?: Helpline[];
}
interface Message { role: 'user' | 'bot'; content: string; created_at?: string; action_card?: ActionCard; }
interface Session { id: number; title: string; created_at: string; is_pinned: boolean; }

export default function ChatbotScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();
  const { isDarkMode } = usePreferences();
  
  // FIX #2: Extract the safe area insets to push the UI above the Android Navigation Bar
  const insets = useSafeAreaInsets();

  // Core Chat State
  const [sessions, setSessions] = useState<Session[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<number | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [customAlert, setCustomAlert] = useState({ visible: false, title: '', message: '' });
  const [keyboardHeight, setKeyboardHeight] = useState(0);
  
  // EXPLICIT AUDIO UI STATE
  const [isListening, setIsListening] = useState(false);
  const [isTranscribing, setIsTranscribing] = useState(false);
  const [recordingDots, setRecordingDots] = useState('');
  
  // FIX #3: Invisible flag to track if the current input was generated by Voice
  const isVoiceModeRef = useRef(false);

  const audioRecorder = useAudioRecorder(RecordingPresets.HIGH_QUALITY);

  // Animation Refs
  const scrollRef = useRef<ScrollView>(null);
  const sidebarAnim = useRef(new Animated.Value(-320)).current;

  useEffect(() => {
    loadSessions();
    if (params.session_id) switchSession(Number(params.session_id));
  }, [params.session_id]);

  useEffect(() => {
    Animated.timing(sidebarAnim, {
      toValue: sidebarOpen ? 0 : -320, duration: 300, easing: Easing.out(Easing.cubic), useNativeDriver: true,
    }).start();
  }, [sidebarOpen]);

  // Animated "Listening..." Dots
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isListening) {
      interval = setInterval(() => {
        setRecordingDots(prev => (prev.length >= 3 ? '' : prev + '.'));
      }, 400);
    } else {
      setRecordingDots('');
    }
    return () => clearInterval(interval);
  }, [isListening]);

  const showCustomAlert = (title: string, message: string) => {
    setCustomAlert({ visible: true, title, message });
  };

  useEffect(() => {
    const show = Keyboard.addListener('keyboardDidShow', (e) => {
      setKeyboardHeight(e.endCoordinates.height);
      scrollDown(); // keep chat scrolled to bottom when keyboard opens
    });
    const hide = Keyboard.addListener('keyboardDidHide', () => {
      setKeyboardHeight(0);
    });
    return () => { show.remove(); hide.remove(); };
  }, []);

  /* =========================================
     BACKEND INTEGRATION
  ========================================= */
  const loadSessions = async () => {
    try {
      const res = await apiClient.get('/core/chat/sessions/');
      setSessions(res.data);
    } catch (e) { console.error("Failed to load sessions", e); }
  };

  const createNewChat = () => {
    setActiveSessionId(null); setMessages([]); setSidebarOpen(false);
  };

  const switchSession = async (id: number) => {
    setActiveSessionId(id); setSidebarOpen(false);
    try {
      const res = await apiClient.get(`/core/chat/session/${id}/`);
      setMessages(res.data);
      if (res.data.length === 0) loadInitialMessage(id);
    } catch (e) { console.error("Switch session failed", e); }
    loadSessions(); 
  };

  const loadInitialMessage = async (id: number) => {
    try {
      const res = await apiClient.get(`/core/chat/initial/?session_id=${id}`);
      if (res.data?.reply) setMessages([{ role: 'bot', content: res.data.reply }]);
    } catch (e) { console.error("Initial message failed", e); }
  };

  const deleteSession = async (id: number) => {
    try {
      await apiClient.delete(`/core/chat/session/${id}/delete/`);
      if (activeSessionId === id) createNewChat();
      loadSessions();
    } catch (e) { console.error("Delete failed", e); }
  };

  const togglePin = async (id: number) => {
    try {
      await apiClient.post(`/core/chat/session/${id}/pin/`);
      loadSessions();
    } catch (e) { console.error("Pin failed", e); }
  };

  const sendMessage = async (customText?: string) => {
    const textValue = customText || input;
    if (!textValue.trim()) return;

    // FIX #3: Capture whether this specific message came from the microphone, then reset it
    const triggerAutoTTS = isVoiceModeRef.current;
    isVoiceModeRef.current = false;

    setMessages((prev) => [...prev, { role: 'user', content: textValue }]);
    setInput(''); setIsTyping(true);
    scrollDown();

    let currentSessionId = activeSessionId;

    try {
      if (!currentSessionId) {
        const sessionSetup = await apiClient.post('/core/chat/session/');
        currentSessionId = sessionSetup.data.session_id;
        setActiveSessionId(currentSessionId);
      }

      const res = await apiClient.post('/core/chat/message/', {
        session_id: currentSessionId, message: textValue
      });

      if (res.data?.reply) {
        setMessages((prev) => [...prev, { role: 'bot', content: res.data.reply, action_card: res.data.action_card }]);
        
        // FIX #3: Automatically speak the reply if the user spoke their message
        if (triggerAutoTTS) {
            speakText(res.data.reply);
        }
      }
      loadSessions();
    } catch (e) {
      setMessages((prev) => [...prev, { role: 'bot', content: "Connection disruption recognized. Let's try again." }]);
    } finally {
      setIsTyping(false); scrollDown();
    }
  };

  const scrollDown = () => {
    setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 150);
  };

  /* =========================================
     PDF EXPORT
  ========================================= */
  const exportChatToPDF = async () => {
    if (!activeSessionId) {
      showCustomAlert("Action Required", "Please select an active chat session to export.");
      return;
    }
    try {
      const activeItem = sessions.find(s => s.id === activeSessionId);
      const chatTitle = activeItem ? activeItem.title : "Wellness Session";
      const exportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });

      const messagesHtml = messages.map(msg => {
        const safeContent = msg.content.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, '<br>');
        if (msg.role === 'user') {
          return `<div style="display: flex; justify-content: flex-end; margin-bottom: 24px; page-break-inside: avoid;">
                    <div style="background-color: #3b82f6; color: #ffffff; padding: 14px 20px; border-radius: 20px 20px 4px 20px; max-width: 80%; font-size: 14px; line-height: 1.6; box-shadow: 0 2px 4px rgba(59, 130, 246, 0.1);">${safeContent}</div>
                  </div>`;
        } else {
          return `<div style="display: flex; align-items: flex-start; gap: 14px; margin-bottom: 24px; page-break-inside: avoid;">
                    <div style="width: 40px; height: 40px; border-radius: 50%; background-color: #f8fafc; border: 1px solid #e2e8f0; display: flex; align-items: center; justify-content: center; flex-shrink: 0;">
                        <svg width="26" height="26" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="50" cy="50" r="45" fill="#EEF2FF" stroke="#C7D2FE" stroke-width="4"/>
                            <circle cx="35" cy="45" r="5" fill="#4F46E5"/>
                            <circle cx="65" cy="45" r="5" fill="#4F46E5"/>
                            <path d="M40 65C40 65 45 70 50 70C55 70 60 65 60 65" stroke="#4F46E5" stroke-width="4" stroke-linecap="round"/>
                        </svg>
                    </div>
                    <div style="background-color: #fef3c7; color: #713f12; padding: 14px 20px; border-radius: 20px 20px 20px 4px; max-width: 80%; font-size: 14px; line-height: 1.6; border: 1px solid #fde047;">${safeContent}</div>
                  </div>`;
        }
      }).join('');

      const htmlContent = `
        <html>
        <head>
            <style>
                body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 20px; color: #1f2937; }
                .header { background: linear-gradient(135deg, #4f46e5, #3b82f6); color: white; padding: 30px; border-radius: 20px; margin-bottom: 40px; }
                .header h1 { margin: 0 0 10px 0; font-size: 26px; }
                .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #9ca3af; border-top: 2px solid #f3f4f6; padding-top: 20px; font-weight: bold; text-transform: uppercase;}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Conversation with Smera</h1>
                <p><strong>Topic:</strong> ${chatTitle}</p>
                <p><strong>Date:</strong> ${exportDate}</p>
            </div>
            <div>${messagesHtml}</div>
            <div class="footer">Securely exported from your Smera Mental Wellness App</div>
        </body>
        </html>
      `;

      const { base64 } = await Print.printToFileAsync({ html: htmlContent, base64: true });
      if (!base64) throw new Error("Failed to generate PDF data.");

      const docDir = FileSystem.documentDirectory;
      if (!docDir) throw new Error("Document directory is unavailable.");
      
      const safePdfPath = `${docDir}Smera_Chat_${Date.now()}.pdf`;

      const fileInfo = await FileSystem.getInfoAsync(safePdfPath);
      if (fileInfo.exists) await FileSystem.deleteAsync(safePdfPath);

      await FileSystem.writeAsStringAsync(safePdfPath, base64, { encoding: FileSystem.EncodingType.Base64 });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(safePdfPath, { UTI: 'com.adobe.pdf', mimeType: 'application/pdf', dialogTitle: 'Export Chat Session' });
      }

    } catch (e: any) {
      console.error(e);
      showCustomAlert("Export Failed", e.message || "Failed to export the chat session securely.");
    }
  };

  /* =========================================
     VOICE (EXPLICIT UI CONTROL + BACKEND STT)
  ========================================= */
  const speakText = (text: string) => {
    Speech.stop(); 
    Speech.speak(text, { rate: 0.95, pitch: 1.0 });
  };

  const handleVoiceInput = async () => {
    try {
      if (isListening) {
        setIsListening(false);
        setIsTranscribing(true);
        // Awaiting stop() ensures the URI is available immediately after
        await audioRecorder.stop();

        if (audioRecorder.uri) {
          await uploadVoiceChunk(audioRecorder.uri);
        } else {
          setIsTranscribing(false);
          showCustomAlert("Error", "Could not capture the audio file.");
        }
      } else {
        const permission = await AudioModule.requestRecordingPermissionsAsync();

        if (permission.granted) {
          // Stop any TTS currently reading out loud
          Speech.stop();
          
          setInput('');
          await audioRecorder.prepareToRecordAsync();
          audioRecorder.record();
          setIsListening(true);
        } else {
          showCustomAlert("Microphone Access", "Please enable microphone permissions in your device settings to talk to Smera.");
        }
      }
    } catch (error: any) {
      setIsListening(false);
      setIsTranscribing(false);
      console.error("Audio Error:", error);
      showCustomAlert("Recording Error", error.message || "Unable to access the microphone system.");
    }
  };

  const uploadVoiceChunk = async (uri: string) => {
    try {
      const formData = new FormData();
      
      const match = /\.([a-zA-Z0-9]+)$/.exec(uri);
      const extension = match ? match[1] : 'm4a';
      const mimeType = extension === 'mp4' ? 'audio/mp4' : `audio/${extension}`;

      formData.append('audio', { 
        uri: Platform.OS === 'android' ? uri : uri.replace('file://', ''), 
        name: `audio.${extension}`, 
        type: mimeType 
      } as any);

      const res = await apiClient.post('/core/chat/stt/', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });

      if (res.data?.text) {
        setInput(res.data.text);
        isVoiceModeRef.current = true; // FIX #3: Mark this input as successfully populated by voice!
      } else {
        showCustomAlert("Transcription Alert", "No speech was detected. Please try again.");
      }
    } catch (e) {
      console.error("STT failed", e);
      showCustomAlert("Transcription Failed", "Could not process your voice. Please try typing or speak more clearly.");
    } finally {
      setIsTranscribing(false);
    }
  };

  /* =========================================
     UI RENDERS
  ========================================= */
  const filteredSessions = sessions.filter(s => (s.title || "New Chat").toLowerCase().includes(searchQuery.toLowerCase()));

  // Explicitly control what displays in the textbox based on manual React State
  let displayValue = input;
  if (isListening) displayValue = `Listening${recordingDots}`;
  else if (isTranscribing) displayValue = "Transcribing...";

  return (
    // FIX #1: Force padding behavior on Android so the keyboard correctly pushes the UI upwards
    <KeyboardAvoidingView
      style={{ flex: 1 }}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      enabled={Platform.OS === 'ios'}>
      <View className="flex-1 bg-neutral-50 dark:bg-black relative">
        <LinearGradient colors={isDarkMode ? ['rgba(63,94,251,0.08)', 'transparent'] : ['rgba(99,102,241,0.1)', 'transparent']} style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 450 }} />

        {/* --- CUSTOM ALERT MODAL --- */}
        <Modal visible={customAlert.visible} transparent animationType="fade">
          <View className="flex-1 items-center justify-center bg-black/60 px-4">
            <View className="w-full max-w-sm bg-white dark:bg-neutral-900 rounded-3xl p-6 border border-slate-200 dark:border-neutral-800 shadow-2xl">
              <Text className="text-xl font-black text-slate-800 dark:text-white mb-2">{customAlert.title}</Text>
              <Text className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed mb-6">{customAlert.message}</Text>
              <Button onPress={() => setCustomAlert({ ...customAlert, visible: false })} className="w-full bg-indigo-600 rounded-xl h-12">
                <Text className="font-bold text-white text-base">Understood</Text>
              </Button>
            </View>
          </View>
        </Modal>

        {/* --- SIDEBAR OVERLAY --- */}
        {sidebarOpen && <TouchableOpacity activeOpacity={1} onPress={() => setSidebarOpen(false)} className="absolute inset-0 bg-slate-900/40 dark:bg-black/70 z-40 backdrop-blur-sm" />}

        {/* --- SIDEBAR --- */}
        <Animated.View style={{ transform: [{ translateX: sidebarAnim }] }} className="absolute top-0 bottom-0 left-0 w-80 bg-white/95 dark:bg-neutral-900/95 border-r border-slate-200/50 dark:border-neutral-800/50 z-50 shadow-2xl pt-14 pb-6 flex-col">
          <View className="px-5 mb-5">
            <Button color="primary" onPress={createNewChat} className="w-full bg-indigo-600 rounded-2xl h-14 shadow-md shadow-indigo-500/20">
              <Plus size={20} color="#ffffff" className="mr-2" />
              <Text className="font-bold text-white text-base">New Conversation</Text>
            </Button>
          </View>

          <View className="px-5 mb-4 relative">
            <View className="absolute left-8 top-3.5 z-10"><Search size={16} color={isDarkMode ? "#6b7280" : "#a3a3a3"} /></View>
            <TextInput 
              value={searchQuery} onChangeText={setSearchQuery} placeholder="Search history..." placeholderTextColor={isDarkMode ? "#6b7280" : "#a3a3a3"}
              className="w-full bg-slate-100/70 dark:bg-black/40 border border-slate-200/40 dark:border-neutral-800 rounded-2xl pl-10 pr-4 py-3 text-sm text-slate-800 dark:text-white"
            />
          </View>
          
          <Text className="px-6 text-[10px] font-black uppercase tracking-widest text-slate-400 mb-3 mt-2">History Log</Text>
          <ScrollView className="flex-1 px-3" showsVerticalScrollIndicator={false}>
            {filteredSessions.map((s) => (
              <TouchableOpacity key={s.id} onPress={() => switchSession(s.id)} className={`p-4 rounded-2xl mb-1.5 flex-row justify-between items-center transition-all ${activeSessionId === s.id ? 'bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-100 dark:border-indigo-500/20' : 'bg-transparent border border-transparent'}`}>
                <View className="flex-row items-center gap-3 flex-1 pr-2">
                  <MessageSquare size={16} color={s.is_pinned ? "#eab308" : (isDarkMode ? "#4b5563" : "#cbd5e1")} />
                  <Text numberOfLines={1} className={`font-bold text-sm flex-1 ${activeSessionId === s.id ? 'text-indigo-900 dark:text-indigo-200' : 'text-slate-600 dark:text-slate-300'}`}>{s.title || "New Chat"}</Text>
                </View>
                <View className="flex-row gap-3">
                  <TouchableOpacity onPress={() => togglePin(s.id)}><Pin size={16} color={s.is_pinned ? "#eab308" : "#94a3b8"} /></TouchableOpacity>
                  <TouchableOpacity onPress={() => deleteSession(s.id)}><Trash2 size={16} color="#f43f5e" opacity={0.7} /></TouchableOpacity>
                </View>
              </TouchableOpacity>
            ))}
          </ScrollView>
        </Animated.View>
          
        {/* --- HEADER --- */}
        <View className="pt-14 pb-4 px-4 bg-white/70 dark:bg-black/50 border-b border-slate-200/40 dark:border-neutral-800/40 flex-row items-center justify-between z-30">
          <View className="flex-row items-center gap-4">
            <TouchableOpacity onPress={() => setSidebarOpen(true)} className="p-2 bg-white dark:bg-indigo-600 border border-slate-200/50 dark:border-neutral-800 rounded-xl items-center justify-center shadow-sm">
              <Menu size={22} className="text-slate-700 dark:text-slate-300" />
            </TouchableOpacity>
            <View className="flex-row items-center gap-3">
              <SmeraAvatar size={40} />
              <View>
                <Text className="font-black text-lg text-slate-800 dark:text-white leading-tight tracking-wide">Smera</Text>
                <View className="flex-row items-center gap-1.5">
                  <View className="w-2 h-2 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.8)]" />
                  <Text className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-wide">Online</Text>
                </View>
              </View>
            </View>
          </View>
          
          <View className="flex-row items-center gap-2">
            {activeSessionId && (
              <TouchableOpacity onPress={exportChatToPDF} className="px-3 py-2.5 bg-indigo-50 dark:bg-indigo-900/30 border border-indigo-200 dark:border-indigo-800/50 rounded-xl flex-row items-center gap-1.5">
                <Download size={14} color={isDarkMode ? "#818cf8" : "#4f46e5"} />
                <Text className="text-md font-bold text-indigo-600 dark:text-indigo-400">Export</Text>
              </TouchableOpacity>
            )}
            <TouchableOpacity onPress={() => router.push('/core/dashboard')} className="px-4 py-2.5 bg-white dark:bg-neutral-900 border border-slate-200/50 dark:border-neutral-800 rounded-xl shadow-sm">
              <Text className="text-md font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Exit</Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* --- MAIN CHAT SCROLL AREA --- */}
        <ScrollView 
          ref={scrollRef} 
          className="flex-1"
          contentContainerStyle={{ padding: 16, paddingBottom: 24, flexGrow: 1, justifyContent: 'flex-end' }}
          showsVerticalScrollIndicator={false}
          onContentSizeChange={() => scrollDown()}
          keyboardShouldPersistTaps="handled"
        >
          {messages.length === 0 ? (
            <View className="flex-1 items-center justify-center">
              <SmeraAvatar size={100} />
              <Text className="text-2xl font-black text-slate-800 dark:text-white tracking-tight mb-2 mt-6 text-center">How can I help you today?</Text>
              <Text className="text-slate-400 dark:text-neutral-500 text-center text-sm mb-8 max-w-sm leading-relaxed">
                Feel free to share what's on your mind or explore some topics below.
              </Text>
              <View className="gap-2.5 w-full max-w-sm">
                {[
                  "Dealing with stress", 
                  "Better sleep habits", 
                  "Just need to chat",
                  "I would like to explore options for professional consultation."
                ].map((suggest, idx) => (
                  <TouchableOpacity key={idx} onPress={() => sendMessage(suggest)} className={`p-4 bg-white dark:bg-neutral-900 border rounded-2xl shadow-sm hover:scale-105 transition-transform ${idx === 3 ? 'border-indigo-200 dark:border-indigo-800/80 bg-indigo-50/50 dark:bg-indigo-900/10' : 'border-slate-200/60 dark:border-neutral-800/80'}`}>
                    <Text className={`font-bold text-sm text-center ${idx === 3 ? 'text-amber-600 dark:text-amber-400' : 'text-slate-600 dark:text-slate-300'}`}>{suggest}</Text>
                  </TouchableOpacity>
                ))}
              </View>
            </View>
          ) : (
            <View className="gap-5">
              {messages.map((msg, i) => (
                <View key={i} className={`flex-row w-full ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  {msg.role === 'bot' && (
                    <View className="mr-3 mt-1 shrink-0"><SmeraAvatar size={32} /></View>
                  )}
                  <View className={`max-w-[85%] ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                    <View className={`p-4 rounded-[1.5rem] ${msg.role === 'user' ? 'bg-blue-600 rounded-tr-sm shadow-md shadow-blue-500/20' : 'bg-[#fef3c7] dark:bg-[#452209] border border-[#fde047] dark:border-[#713f12] rounded-tl-sm shadow-sm'}`}>
                      <Text className={`text-base font-medium leading-relaxed ${msg.role === 'user' ? 'text-white' : 'text-[#713f12] dark:text-[#fef3c7]'}`}>
                        {msg.content}
                      </Text>

                      {msg.action_card?.type === 'consultation' && (
                        <TouchableOpacity onPress={() => router.push('/consultation/consultation')} className="mt-4 bg-blue-600 border border-blue-500 p-3 rounded-xl flex-row items-center justify-between">
                          <Text className="font-bold text-sm text-white">{msg.action_card.title}</Text>
                          <HeartHandshake size={18} className="text-white" />
                        </TouchableOpacity>
                      )}

                      {msg.action_card?.type === 'critical_support' && (
                        <View className="mt-5 bg-white/40 dark:bg-transparent border border-black/5 dark:border-transparent p-4 rounded-xl gap-3">
                          <View className="flex-row items-center gap-2 mb-1">
                            <ShieldAlert size={18} className="text-red-700 dark:text-red-400" />
                            <Text className="font-bold text-base text-red-700 dark:text-red-400">{msg.action_card.title}</Text>
                          </View>
                          <View className="gap-2">
                            {msg.action_card.helplines?.map((line, lIdx) => (
                              <View key={lIdx} className="flex-row justify-between items-center bg-white/60 dark:bg-black/20 px-3 py-2 rounded-lg">
                                <Text className="text-sm text-[#713f12] dark:text-yellow-100">{line.name}</Text>
                                <Text className="text-sm font-bold text-[#713f12] dark:text-yellow-100">{line.phone}</Text>
                              </View>
                            ))}
                          </View>
                          <Button className="mt-2 w-full bg-blue-600 rounded-lg" onPress={() => router.push('/consultation/consultation')}>
                            <Text className="font-bold text-white text-sm">Book a Consultation</Text>
                          </Button>
                        </View>
                      )}
                    </View>

                    {msg.role === 'bot' && (
                      <TouchableOpacity onPress={() => speakText(msg.content)} className="mt-2 ml-1 flex-row items-center gap-1.5 px-3 py-1.5 bg-slate-100 dark:bg-neutral-800 rounded-full border border-transparent dark:border-neutral-700 opacity-80">
                        <Volume2 size={12} color={isDarkMode ? "#94a3b8" : "#64748b"} />
                        <Text className="text-[10px] font-black text-slate-500 dark:text-slate-400 uppercase tracking-widest">Listen</Text>
                      </TouchableOpacity>
                    )}
                  </View>
                </View>
              ))}
              {isTyping && (
                <View className="flex-row items-center gap-3 mt-1">
                  <SmeraAvatar size={32} />
                  <View className="bg-white/90 dark:bg-neutral-900/95 border border-violet-200/70 dark:border-violet-500/20 px-5 py-4 rounded-3xl rounded-tl-sm shadow-lg shadow-violet-500/5">
  
                    <View className="flex-row items-center gap-3">
                      <View>
                        <Text className="text-slate-800 dark:text-slate-100 font-semibold text-sm">
                          Smera is thinking
                        </Text>
                      </View>
                      
                      <View className="flex-row items-center gap-1">
                        <View className="w-2 h-2 rounded-full bg-violet-500" />
                        <View className="w-2 h-2 rounded-full bg-violet-400 opacity-70" />
                        <View className="w-2 h-2 rounded-full bg-violet-300 opacity-50" />
                      </View>

                    </View>
                  </View>
                </View>
              )}
            </View>
          )}
        </ScrollView>

        {/* --- FIXED BOTTOM INPUT AREA --- */}
        <View 
          className="p-4 bg-white/90 dark:bg-neutral-900/90 backdrop-blur-2xl border-t border-slate-200/60 dark:border-neutral-800 shadow-[0_-10px_40px_rgba(0,0,0,0.05)] dark:shadow-[0_-10px_40px_rgba(0,0,0,0.3)]"
          // FIX #2: Dynamically add the device's bottom safe inset height so the bar is never hidden behind Android system buttons
          style={{ 
            paddingBottom: Math.max(insets.bottom + 8, 24),
            marginBottom: Platform.OS === 'android' ? keyboardHeight : 0
          }}>
          <View className="flex-row items-end gap-2 bg-slate-50 dark:bg-black/50 rounded-[2rem] p-1.5 border border-slate-200/80 dark:border-neutral-700 shadow-inner">
            
            <TextInput 
              value={displayValue} 
              onChangeText={(val) => {
                  setInput(val);
                  // FIX #3 (Safety): If the user manually clears the text box, cancel the auto-TTS voice flag
                  if (val === '') isVoiceModeRef.current = false;
              }} 
              placeholder="Message Smera..." 
              placeholderTextColor={isDarkMode ? "#6b7280" : "#a3a3a3"} 
              multiline 
              editable={!isTranscribing && !isListening}
              className={`flex-1 max-h-32 min-h-[44px] px-4 pt-3.5 pb-3 text-base font-medium ${isListening || isTranscribing ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-900 dark:text-white'}`}
            />
            
            <View className="flex-row items-center gap-1.5 mb-1 mr-1">
              <TouchableOpacity onPress={handleVoiceInput} disabled={isTranscribing} className="relative w-11 h-11 items-center justify-center">
                {isListening && (
                  <View className="absolute inset-0 bg-red-500 rounded-full animate-ping opacity-50" />
                )}
                <View className={`absolute inset-0 w-11 h-11 rounded-full items-center justify-center shadow-sm ${isListening ? 'bg-red-500 shadow-red-500/40' : 'bg-white dark:bg-neutral-800 border border-slate-200/60 dark:border-neutral-700'}`}>
                  {isTranscribing ? <ActivityIndicator size="small" color={isDarkMode ? "#ffffff" : "#4f46e5"} /> : isListening ? <MicOff size={18} color="#ffffff" /> : <Mic size={18} color={isDarkMode ? "#6b7280" : "#94a3b8"} />}
                </View>
              </TouchableOpacity>

              <TouchableOpacity onPress={() => sendMessage()} disabled={!input.trim() || isTranscribing || isListening} className={`w-11 h-11 rounded-full items-center justify-center transition-all ${input.trim() ? 'bg-blue-600 shadow-md shadow-blue-500/30' : 'bg-slate-200 dark:bg-neutral-800 border border-transparent dark:border-neutral-700'}`}>
                <Send size={18} color={input.trim() ? "#ffffff" : (isDarkMode ? "#4b5563" : "#94a3b8")} className="ml-1" />
              </TouchableOpacity>
            </View>
          </View>
          <Text className="text-center text-[10px] text-slate-800/80 dark:text-slate-400/80 font-bold mt-4 uppercase tracking-widest">Smera can make mistakes. Verify important info.</Text>
        </View>

      </View>
    </KeyboardAvoidingView>
  );
}