# Generated by Django 6.0.4 on 2026-05-12 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('education', models.TextField()),
                ('university', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.IntegerField()),
                ('patients_treated', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('session_duration', models.IntegerField(default=30)),
                ('hospitals', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('research_work', models.TextField(blank=True)),
                ('innovations', models.TextField(blank=True)),
                ('live_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy')], default='offline', max_length=20)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_types', models.ManyToManyField(blank=True, to='consultation.consultationtype')),
                ('categories', models.ManyToManyField(blank=True, to='consultation.mentalhealthcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=30)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20)),
                ('chamber_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='consultation.counselor')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='consultation.counselor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='booked', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rescheduled_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('hospital_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.availabilityslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.counselor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='consultatio_status_80c414_idx'), models.Index(fields=['payment_status'], name='consultatio_payment_5dea54_idx'), models.Index(fields=['created_at'], name='consultatio_created_32cc40_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['date'], name='consultatio_date_280621_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['is_booked'], name='consultatio_is_book_8ba04e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('counselor', 'date', 'time')},
        ),
        migrations.AddIndex(
            model_name='counselor',
            index=models.Index(fields=['name'], name='consultatio_name_e1edbb_idx'),
        ),
        migrations.AddIndex(
            model_name='counselor',
            index=models.Index(fields=['live_status'], name='consultatio_live_st_f54b74_idx'),
        ),
    ]
