# Generated by Django 6.0.2 on 2026-05-26 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mode'], name='consultatio_mode_416f38_idx'), models.Index(fields=['available'], name='consultatio_availab_ba1eee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('booked', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='consultation.counselor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=30, null=True)),
                ('queue_number', models.IntegerField(blank=True, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.counselor')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.slot')),
            ],
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['date', 'booked'], name='consultatio_date_5fdc5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('counselor', 'date', 'time')},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'slot'), name='unique_user_slot'),
        ),
    ]
