# Generated by Django 6.0.2 on 2026-05-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='counselor',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
