# Generated by Django 6.0.2 on 2026-05-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_counselor_rating_counselor_total_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
