# Generated by Django 6.0.2 on 2026-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_counselor_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='token',
            new_name='access_key',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checked_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='queue_number',
        ),
        migrations.AddField(
            model_name='counselor',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=30),
        ),
    ]
